### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kirooshu** [varnish/varnish-nagios#11]
Guys, do you plan to cut a new release now that you have varnish 4.1 support? We are looking into using the module but do not like the idea of taking a snapshot from master if you are very close to cutting a Github release.

Thank you in advance!

**Comment by komapa** [comment]
Bump! @denisbr

**Comment by denisbr** [comment]
Hi, no release as such is planned. Fixing the 4.1 support was done to avoid having broken code.

**Comment by komapa** [comment]
Do you mind cutting a release? We have build tools which are much better
suited for working with release tags than code from master. Also it is hard
to track what sha we take from master, etc.

Thank you in advance!
