### ISSUE TITLE
Unknown parameter 'usage' && 'uptime'

### ISSUE THREAD

**Issue by davidak** [varnish/varnish-nagios#6]
i have sucessfully built the check on ubuntu 14.04 with varnish 4 from their repo.

```
# ./check_varnish -p ratio -w 80: -c 60:
VARNISH CRITICAL: Cache hit ratio (51)|ratio=51
# ./check_varnish -p usage
Unknown parameter 'usage'
# ./check_varnish -p uptime
Unknown parameter 'uptime'
```

**Comment by denisbr** [comment]
Hi david,

```check_varnish``` relies on varnishstat to get its counters. In Varnish 4 there is no ```usage``` counter anymore. Your best bet is to do ```varnishstat -l``` and find the counter you would like to monitor.
You might want to monitor the ```Bytes available``` counter, but its name depends on your storage pool name, on my setup this works:
```./check_varnish -p SMA.s0.g_space``

**Comment by davidak** [comment]
@denisbr thanks for the info. the output of `check_varnish -h` should then be updated.

>In addition, the following parameters are available:

**Comment by keith4** [comment]
"In Varnish 4 there is no usage counter anymore."

From what I see, there's no "usage" counter in Varnish 3(.0.2) either?

./check_varnish -p usage
Unknown parameter 'usage'

# varnishd -V
varnishd (varnish-3.0.2 revision 55e70a4)
